version: '3.8'

services:
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dental_clinic_db
      MYSQL_USER: dental_clinic_user
      MYSQL_PASSWORD: Gentifit2024
      MYSQL_ROOT_PASSWORD: Gentifit2024
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
